name: ypage

services:

  backend:
    build: 
      args:
        - NODE_ENV=development
      context: backend
      target: development
    command: npm run dev
    environment:
      - DATABASE_DB=users
      - DATABASE_USER=ypage_user
      - DATABASE_PASSWORD=/run/secrets/db-user-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - 80:80
      - 2350:2350
      - 2351:2351
    secrets:
      - db-user-password
    networks:
      - public
      - private
    depends_on:
      - db

  db:
    image: mariadb:11.3.2-jammy
    restart: always
    environment:
      - MARIADB_DATABASE=users
      - MARIADB_USER=ypage_user
      - MARIADB_USER_PASSWORD_FILE=/run/secrets/db-user-password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-root-password
    volumes:
      - ypage-db:/var/lib/mysql
    #expose:
    # - 3306
    networks:
      - private
networks:
  public:
  private:

secrets:
  db-root-password:
    file: db/root_password.txt
  db-user-password:
    file: db/user_password.txt

volumes:
  ypage-db:
